#!/bin/bash

# Copyright 2022 ZhengPu Shi
# This file is part of CoqMatrix. It is distributed under the MIT
# "expat license". You should have recieved a LICENSE file with it.


# 为什么需要这个脚本？为了完成OCaml程序的编译，需要解决一些问题
# 1. 抽取的OCaml程序需要处理的问题
# a. coq_R 的两个函数替代
# b. predP 的定义中参数不匹配的处理
# 2. coq_X 与 float，在REPL中正常，但编译时类型不匹配，所以合并为同一个文件
# a. 头部 #use 等指示符的去除

# 具体做法
# 1. 创建新目录 build，并进入该目录
# 2. 将生成的 matrix.ml 和手写的 test.ml 拷贝到该目录
# 3. 修正 matrix.ml 的部分代码
# 4. 删掉 test.ml 头部的部分信息，并追加到 matrix.ml 文件
# 5. 利用 ocamlfind 编译，因为需要传入 unix 等第三方库。
# 6. 编译

# welcome
echo "Compile preparing..."

# 进入脚本所在目录
cd `dirname $0`
dir=`pwd`

# 建立构建目录
mkdir -p build

# 进入该目录
cd build

# 拷贝需要的文件
cp ../matrix.mli ./
cp ../matrix.ml ./
cp ../test.ml ./
cp ../Makefile ./

# 修正文件
sed -i 's/coq_Rabst : cReal -> coq_R/coq_Rabst : __/' matrix.mli
sed -i 's/coq_Rrepr : coq_R -> cReal/coq_Rrepr : __/' matrix.mli
sed -i 's/coq_Rabst : cReal -> coq_R/coq_Rabst : __/' matrix.ml
sed -i 's/coq_Rrepr : coq_R -> cReal/coq_Rrepr : __/' matrix.ml
sed -i "s/simplPred (fun _ -> true)/fun (_:'a1) -> true/" matrix.ml
sed -i 's/^#.*//' test.ml

# 合并文件
cat test.ml >> matrix.ml

# 编译
make

# 拷贝输出到父目录
cp matrix ../

# 删除中间目录
cd ../
rm build -r

# 通知
echo 'Compile finished. output file is "matrix"'
